---
deployment:
  tasks:
    - export DEPLOYPATH=/home/green64/public_html
    - export DEPLOYPATH1=/home/green64/public_html/scripts
#this variant below is working well
    - /bin/cp  public_html/index.php $DEPLOYPATH
#the code below works fine

#code below for deploing to scripts folder(working well) 
    - /bin/cp -R public_html/scripts $DEPLOYPATH

#this code is for deploing to other_css
    - /bin/cp -R public_html/other_css $DEPLOYPATH
#this code is for deploing to js
    - /bin/cp -R public_html/js $DEPLOYPATH
#this code is for deploing to database_connection
    - /bin/cp -R public_html/database_connection $DEPLOYPATH
#this code is for deploing to admin folder
    - /bin/cp -R public_html/admin $DEPLOYPATH
#this code is for deploing to images folder
    - /bin/cp -R public_html/images $DEPLOYPATH
#this code is for deploing to app folder
    - /bin/cp -R public_html/app $DEPLOYPATH