<?php include CONTENT . 'header.phtml'; ?>

<h3>Товар не був доданий успішно</h3>


   <div id="back_home_admin_button">
          <a href="<?php echo $url; ?>://greenbro<?php echo ".$domen_part/admin/app_managing_page"; ?>">go to previous page</a>
   </div>          


<!-- the element below makes our page to right side  -->
<div id="size_of_page_adding"></div>


<?php include CONTENT . 'footer.phtml'; ?>