<?php include CONTENT . 'header.phtml'; ?> 

  <div id="unsuccessful_order">
    <p>Виникли певні складнощі при оформленні замовлення, спробуйте ще раз.</p>
    <p>Для допомоги або поради ви можете написати нам перейшовши за посиланням 
     <a href="http://greenbro.com/home/contactUs"><strong>Зворотній зв'язок:)</strong></a>                                                         
    </p>
  </div>

 <?php include CONTENT . 'footer.phtml'; ?>
    