<?php include CONTENT . 'header.phtml'; ?>

<!-- the method below checking was validation success or not -->
<?php adminController::static_access_control_manager(); 

      // the code below includes admin add_new_manager page
      include CONTENT . 'admin/add_new_manager_page.content.php';
?>

<!-- the button below for displaying and hidding add_new_manager_form -->
<input id="button_add_new_manager" type="button" value="Show add new manager form" onclick="display_add_new_manager_form()"/>

<!-- the code below for adding new items to DB-->
<title>Page_for_managing</title>
    

<body>

<!-- This part of page below for adding new goods -->
<form id= "manage_goods" name="manage_goods"  method="POST" enctype="multipart/form-data"
    action="<?php echo $url; ?>://greenbro<?php echo ".$domen_part"; ?>/addItem/call_add_new_product" >
    </span><br>
       <!-- For name -->
       <label for="products_name">Products_name</label>
       <input id="products_name" type="text" name="products_name" class="menu" pattern="^[А-Яа-яЁё\s]+$ 0-9]{3,110}" placeholder="Введіть найменування товару" required><span></span><br>
       <!-- For brand_name -->
       <label for="brand_name">Name of brand</label>
       <input id="brand_name" type="text"  name="brand_name" class="menu" pattern="^[А-Яа-яЁё\s]+$ 0-9]{5,110}" required placeholder="Введіть ім'я бренду"><span></span><br>
       <!-- For brand_id -->
       <hr>
       <label class="pic" for="category_of_products">Enter category of goods</label>
       <input type="checkbox" name="category_of_products[]" value="products" checked> Products category
       <input type="checkbox" name="category_of_products[]" value="clothes"> Clothes category
       <input type="checkbox" name="category_of_products[]" value="goods"> Goods category
       <input type="checkbox" name="category_of_products[]" value="books"> Books category <br>
       <hr>
       <!-- For mini_description -->
       <label for="mini_description">Mini description</label>               
       <input id="mini_description"   type="text" name="mini_description" class="menu" pattern="^[А-Яа-яЁё\s]+$  0-9]{5,200}" placeholder="Введіть коротке описання товару" required><span></span><br>
             <!-- For mini_description -->
             
             <!-- For description -->
             <hr>
        <p id="description_name" for="description">Description of goods</p>
          <textarea id="add_item_description" name="description" class="menu" pattern="^[А-Яа-яЁё\s]+$   0-9]{5,600}" placeholder="Введіть описання товару" required></textarea>  <br>
            <hr>
            <!-- For description -->
            

        <!-- Upload images -->
        <!-- You add this only image name, after that you have to upload image into folder image of host -->
       

       
        <div class="for_images">
            <!-- the code below for uploading main image -->
            <label id="main_image">Main image download</label>
        <div>
           
        <p><input type="file" name="main_image" accept=".jpg, .jpeg, .png" onchange="loadFile(event)"></p>
        <img id="output"/>
           </div><br>
        <!-- the code below for uploading images -->
         <p id="multi_image">Multiple download additional images:</p>
        <!-- the code below makes limitation for file size -->
        <div>
        <input type="hidden" name="MAX_FILE_SIZE" value="30000" />
        <p><input type="file" id="fileMulti" name="fileMulti[]" accept=".jpg, .jpeg, .png"  multiple/></p>
        <span id="outputMulti"></span>
          </div>
            </div>




       <!-- Set a price -->
       <label for="set_price">Set price</label>
       <input id="set_price" type="text" name="set_price" class="menu" pattern="[0-9]{2-10}"  placeholder="Встановіть ціну" required><span></span><br>
        <!-- Set it if you have discount for this product -->
       <label for="sale">Bargain sale </label>
       <input id="sale" value="50" type="text" name="sale" class="menu" pattern="[0-9]{1,30}" placeholder="Розпродаж товарів" required><span></span><br>
        <!-- Quantity of products -->
        <label for="quantity">Quantity of products</label>
       <input id="quantity" value="50"  type="text" name="quantity" class="menu" pattern="[0-9]{1-5}" placeholder="Кількість товарів" required><span></span><br>
          <!-- Datetime -->
          <hr>
        <label id="datetime" for="datetime">Date and time</label>
        <input type="checkbox" name="set_time" value="set_time" checked> Встановити поточний час та дату
        <input type="checkbox" name="unset_time" value="unset_time"> Не встановлювати час та дату  <br>
          <hr>   
        <!-- Visible or invisible -->
        <label  id="visible" for="visible">Visible of products</label>
        <input type="checkbox" name="visible" value=1 checked> Відображувати товар
        <input type="checkbox" name="visible" value=0 > Не відображувати товар  <br>


 <div class="button">
<input type="submit" value="Enter" /> 
 </div>
</form>
<!-- end of adding part of page -->








<!-- the element below makes our page to right side  -->
<div id="add_new_manager_size_of_page"></div>

<div id="back_home_admin_button">
    <a href="<?php echo $url; ?>://greenbro<?php echo ".$domen_part" . "/admin/call_unset_access_session"; ?>">Exit from managing page</a>
</div>

<?php include CONTENT . 'footer.phtml'; ?>