<?php
// the code below gets actual environment(url, domen_part)
$wrapper_obj = new WrapperController();
$domen_part = $wrapper_obj->get_domen_part(); 
$url = $wrapper_obj->get_url();


// gets object  from View 
$action = $this->getAction();
?>

<!DOCTYPE html>
<html lang="en">
  <!-- the code for webmanifest has to be edit in production  -->
<link rel="manifest" href="<?php echo $url; ?>://greenbro<?php echo ".$domen_part"; ?>/site.webmanifest">
<!-- <link rel="manifest" href="manifest.webmanifest"> -->
<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
     <!-- from index.php older version -->
     <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&amp;subset=cyrillic" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/other_css/normalize.css" media="all">
    <link rel="stylesheet" type="text/css" href="/other_css/bootstrap-grid.min.css" media="all">
    <link rel="stylesheet" type="text/css" href="/other_css/goodsNew.css" media="all">
    <link rel="stylesheet" type="text/css" href="/other_css/validation.css" media="all">
    <link rel="stylesheet" type="text/css" href="/lib/simplebar.css" media="all">
    <!-- css for product-list.model.php  -->
    <link rel="stylesheet" type="text/css" href="/other_css/products-item.css" media="all">
    <!-- css for product-item-tab in comment section  -->
    <link rel="stylesheet" type="text/css" href="/other_css/products-item-tab.css" media="all">
    <!-- css below for comments block  -->
    <link rel="stylesheet" type="text/css" href="/other_css/comments-style.css" media="all">
    <!-- css  below for rating of comments block  -->
    <link rel="stylesheet" type="text/css" href="/other_css/star-rating-style.css" media="all">
    <!-- css below for private policy pages -->
    <link rel="stylesheet" type="text/css" href="/other_css/private-policy.css" media="all">
    
     <!-- for validation form with AJAX -->
     <!-- <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script> -->
     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" />
    <!-- code for validation form with AJAX above -->

    <!-- code below for js comments section  -->
    <script defer src="/js/rating-script.js"></script>
    <script defer src="/js/comment-script.js"></script>

    <!-- css_for_contact.php -->
    <link rel="stylesheet" type="text/css" href="../other_css/contact_css.css">
    <!--js-script captcha by google for contact page-->
   <script src='https://www.google.com/recaptcha/api.js?hl=uk' async defer></script>

    <!-- this part was in footer in older version  -->
    <!-- <script defer src="/lib/jquery-3.3.1.js"></script> -->
    <script defer src="/js/item_cart_script.js"></script>
    <script defer src="/lib/simplebar.min.js"></script>
    <script defer src="/js/validation-script.js"></script>
    <!-- the code below for ajax login and logout system  -->
    <script defer src="/js/ajax-validation-script.js"></script>
    

    <link rel="apple-touch-icon" sizes="180x180" href="images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="images/favicon-16x16.png">
    
    <link rel="mask-icon" href="images/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="apple-mobile-web-app-title" content="GreenBro">
    <meta name="application-name" content="GreenBro">
    <meta name="msapplication-TileColor" content="#ffc40d">
    <meta name="theme-color" content="#ffffff">


    <title><?php echo (isset($this->page_title) ? $this->page_title : 'Welcome:)');?></title>
</head>
<body>



<!-- we add this empty tag only for footer function "up" -->
<section id="catalog"></section>
    
</body>
</html>

<header class="header" id="header">
      <div id="main_container">
            
                   <a id="link_logo" href="/">
                   <!-- need not change the url below  -->
                   <img id="logo_img" src="https://greenbro.net/images/imgonline-com-ua-Crop-oeaYXY1h2v0.jpg" width="140px" alt="Logo_of_Greenbro"></a>
                  
                    <div id="burger-menu-button" class="burger-menu-button">
                        <div id="line-1"></div>
                        <div id="line-2"></div>
                        <div id="line-3"></div>
                    </div>
    
                    <div id="burger-menu" class="burger-menu">
                       <ul>
                          <li><a href="//greenbro.<?php echo $domen_part; ?>/food/show_food">Продукти</a></li>
                          <li><a href="//greenbro.<?php echo $domen_part; ?>/clothes/show_clothes">Одяг</a></li>    
                          <li><a href="//greenbro.<?php echo $domen_part; ?>/goods/show_goods">Речі</a></li>
                          <li><a href="//greenbro.<?php echo $domen_part; ?>/book/show_books">Література</a></li>
                          <li><a href="//greenbro.<?php echo $domen_part; ?>/home/allThings">Все разом</a></li>
                          <li><a href="//greenbro.<?php echo $domen_part; ?>/home/paymentShipping">Оплата і доставка</a></li>
                          <li><a href="//greenbro.<?php echo $domen_part; ?>/home/contactUs">Контакти</a></li>	
                       </ul>
                    </div>
                    
                <div class="main_menu">
<?php                 
require_once "sidebar.php";




// TO DO burger menu doesn't work 
echo "</div>
      </div>
</header> ";

echo "<div class=\"validation_window\">";
// the code below for log in window 
require_once "validation/login.content.php";
// the code below for registration window 
require_once "validation/registration.content.php";




//  the div below closes div block  
echo "</div>";

