<!-- TO DO  -->
<li class="user_info_block" id="user_info_block_id" onclick=display_menu()><a class="user_info_block">  
	<!-- the code below displays casual image for user   -->
    <img class="user_info_block" src="https://greenbro.net/images/image_for_validation/user_image_arrow.png" id="log_inout_img" alt="User casual image">
    <!-- display user name from casual case  -->
    <?php echo $_SESSION['user_name']; ?>
</a></li>

